WIP:feat: add boilerplate files for generic zephyr driver
arribada/arducam-driver-zephyr pull request #2
Opened 2023-08-04 15:12 UTC by anujdeshpande

2023-08-07 10:09 UTC, Bucknalla commented
I think your header file has an extra '.' after the file name

2023-09-22 10:20 UTC, Bucknalla requested changes
I'm being a bit more picky here as this potentially needs to be a good example driver for other projects to use. Using https://github.com/zephyrproject-rtos/zephyr/blob/main/.clang-format for code formatting.

2023-09-22 10:20 UTC, Bucknalla commented on arducam_mega.c
> +uint8_t cameraBusRead(uint8_t address)
camera_bus_read

2023-09-22 10:20 UTC, Bucknalla commented on arducam_mega.c
> +uint8_t cameraReadReg(uint8_t addr)
camera_read_reg

2023-09-22 10:20 UTC, Bucknalla commented on arducam_mega.c
> +int received_length = 0;
Can we better organise this and change the variable scope from global to their corresponding function?

2023-09-22 10:20 UTC, Bucknalla commented on arducam_mega.c
> +#define SOME_REQUIRED_LEN 30
Better name for this define, something with a bit more clarity?

2023-09-22 10:20 UTC, Bucknalla commented on arducam_mega.c
> +	int ret;
Move to top of function

2023-09-22 10:20 UTC, Bucknalla commented on arducam_mega.c
> +			k_sleep(K_MSEC(3000));
Why is this neccessary?

2023-09-22 10:20 UTC, Bucknalla commented on arducam_mega.c
> +void camera_wait_idle()
Can we do this a better way? Or is the only way for the camera to tell us that it is idle, is by setting its register?

2023-09-22 10:20 UTC, Bucknalla commented on arducam_mega.c
> +	k_sleep(K_MSEC(1000));
I assume this is what Arducam are doing?

2023-09-22 10:20 UTC, Bucknalla requested changes
I'm being a bit more picky here as this potentially needs to be a good example driver for other projects to use. Using https://github.com/zephyrproject-rtos/zephyr/blob/main/.clang-format for code formatting.

2023-09-22 15:21 UTC, anujdeshpande commented on arducam_mega.c
> +			k_sleep(K_MSEC(3000));
It isn't - it's from when I was using it for testing something. Removed!

2023-09-22 15:58 UTC, anujdeshpande commented on arducam_mega.c
> +void camera_wait_idle()
We keep reading a reg till it has a specific value - which indicates that we can continue to the next operation. Arducam's lib doesn't have a different way of doing this - perhaps when they get us the datasheet we can revisit this

2023-10-03 10:23 UTC, closed without merging