Add single read
arribada/arducam-driver-zephyr pull request #3
Opened 2023-10-03 10:23 UTC by anujdeshpande

2023-10-03 12:39 UTC, Bucknalla requested changes
Looks good generally, we'll merge this one and leave the burst open while we wait to solve the weird issues we're having.

2023-10-03 12:39 UTC, Bucknalla commented on arducam_mega.c
> +	/* struct arducam_mega_config *cfg = dev->config; */
Can we remove comments like this before we go to merge the initial release?

2023-10-03 12:39 UTC, Bucknalla commented on arducam_mega.c
> +#include "arducam_mega.h"
Have you run this through `clang-format` yet?

2023-10-03 12:39 UTC, Bucknalla commented
Also please do a rebase and squash :)

2023-10-04 08:47 UTC, anujdeshpande commented
@Bucknalla Can you take a look again? Have
- squashed
- run clang-format
- removed commented code

2023-10-06 09:56 UTC, Bucknalla commented
@anujdeshpande can you please push the `clang-format` config file you're using? We should match the zephyr one

2023-10-06 10:05 UTC, Bucknalla requested changes

2023-10-06 10:05 UTC, Bucknalla commented on arducam_mega.c
> +int arducam_mega_take_picture(CAM_IMAGE_MODE mode,
What is the difference between 'take' and 'save' photo?

2023-10-06 10:05 UTC, Bucknalla commented on arducam_mega.c
> +  uint8_t headFlag = 0;
Styling inconsistency -> uint8_t imageData, imageDataNext, headFlag = 0

2023-10-06 10:05 UTC, Bucknalla commented on arducam_mega.c
> +#include <zephyr/device.h>
Missing license

2023-10-06 10:05 UTC, Bucknalla commented on arducam_mega.h
> +#ifndef __ARDUCAM_MEGA_H__
Missing license

2023-10-06 10:09 UTC, anujdeshpande commented on arducam_mega.c
> +int arducam_mega_take_picture(CAM_IMAGE_MODE mode,
Take keeps it on the cameras buffer

When the app starts I take a photo to warm up the camera - but I don't save it. After that I take and save photos as per the config

2023-10-06 10:25 UTC, Bucknalla commented on arducam_mega.c
> +int arducam_mega_take_picture(CAM_IMAGE_MODE mode,
Perhaps we can tidy this up so we share some code between the two functions, so save utilises take but with extra logic to grab the photos after capture

2023-10-06 10:26 UTC, Bucknalla commented on arducam_mega.c
> +int arducam_mega_take_picture(CAM_IMAGE_MODE mode,
I also this 'take' -> 'capture' it's a bit more clear and explains the whole 'save' / 'capture' difference

2023-10-09 08:42 UTC, anujdeshpande commented on arducam_mega.c
> +  uint8_t headFlag = 0;
```
/home/anuj/arribada/arribada-workspace/time-lapse-zephyr.git/arducam-driver-zephyr/arducam_mega.c:154:28: note: 'imageDataNext' was declared here
  154 |         uint8_t imageData, imageDataNext, headFlag = 0;
```

2023-10-09 09:19 UTC, Bucknalla requested changes
Almost there! Just a couple of tiny language points that make things a little more uniform.

2023-10-09 09:19 UTC, Bucknalla commented on arducam_mega.c
> +uint8_t cameraReadByte()
camera_read_byte()

2023-10-09 09:19 UTC, Bucknalla commented on arducam_mega.c
> +int arducam_mega_capture_picture(CAM_IMAGE_MODE mode, CAM_IMAGE_PIX_FMT pixel_format)
arducam_mega_capture_image

Let's use image instead of picture

2023-10-09 09:19 UTC, Bucknalla commented on arducam_mega.c
> +int arducam_mega_get_cameraid()
arducam_mega_get_id

2023-10-09 09:19 UTC, Bucknalla commented on arducam_mega.c
> +int arducam_mega_capture_picture(CAM_IMAGE_MODE mode, CAM_IMAGE_PIX_FMT pixel_format)
Across other functions too

2023-10-31 15:38 UTC, Bucknalla commented
Merging this so we have a working main, will ideally merge bursting at some point in the future

2023-10-31 15:38 UTC, merged